version: '3.8'

services:
  jwt-auth-service:
    build: ./
    command: sh -c "sleep 2 && ./jwt-auth-service"
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - CONFIG_PATH=./config/dev.yaml
  db:
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=jwt-auth-db
    ports:
      - "5436:5432"

volumes:
  postgres-data: