version: '3.8'

services:
  jwt-auth-service:
    build: ./
    command: sh -c "sleep 10 && ./jwt-auth-service"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty
      - CONFIG_PATH=config/config.yaml
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=jwt-auth-db
    ports:
      - "5436:5432"
