version: "3"

tasks:
  AuthServiceLocal:
    desc: "start AuthService in docker in local environment"
    aliases:
      - authlocal
    cmds: 
      - "docker-compose up --build -d postgres"
      - "docker-compose up --build -d jwt-auth-service-local"
  AuthServiceDevl:
    desc: "start AuthService in docker in dev environment"
    aliases:
      - authdev
    cmds: 
      - "docker-compose up --build -d postgres"
      - "docker-compose up --build -d jwt-auth-service-dev"
  AuthServiceProd:
    desc: "start AuthService in docker in prod environment"
    aliases:
      - authprod
    cmds: 
      - "docker-compose up --build -d postgres"
      - "docker-compose up --build -d jwt-auth-service-prod"
  AuthServiceDB:
    desc: "start AuthService database"
    alliases:
      - db
    cmd: "docker-compose up --build -d postgres"