env: "dev"
http_server:
  host: "jwt-auth-service-dev"
  port: "8002"
  timeout: 4s
  idle_timeout: 60s
db:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "jwt-auth-db"
  sslmode: "disable"