env: "local"
http_server:
  host: "jwt-auth-service-local"
  port: "8000"
  timeout: 4s
  idle_timeout: 60s
db:
  username: "postgres"
  host: "auth-db"
  port: "5432"
  dbname: "jwt-auth-db"
  sslmode: "disable"