env: "prod"
http_server:
  host: "jwt-auth-service-prod"
  port: "8003"
  timeout: 4s
  idle_timeout: 60s
db:
  username: "postgres"
  host: "postgres"
  port: "5432"
  dbname: "jwt-auth-db"
  sslmode: "disable"